# Generated by Django 5.2.1 on 2026-03-29 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category_mapping',
                'indexes': [models.Index(fields=['keyword'], name='category_ma_keyword_98205a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyExpenseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cash_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lunch', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recharge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tea', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'daily_expense_summary',
                'indexes': [models.Index(fields=['date'], name='daily_expen_date_6d2c47_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('category', models.CharField(default='other', max_length=32)),
                ('source_file', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['date'], name='transaction_date_7edf95_idx'), models.Index(fields=['category'], name='transaction_categor_45fcdd_idx'), models.Index(fields=['type'], name='transaction_type_840495_idx')],
            },
        ),
    ]
