# Generated by Django 5.1.6 on 2026-04-13 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_rename_account_number_to_upi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseJobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parse_job_status',
            },
        ),
        migrations.RemoveIndex(
            model_name='accountcategorymapping',
            name='account_cat_account_8b740e_idx',
        ),
        migrations.RenameIndex(
            model_name='accountcategorymapping',
            new_name='account_cat_priorit_37240b_idx',
            old_name='account_cat_priorit_5feb3f_idx',
        ),
        migrations.RenameIndex(
            model_name='regexcategorymapping',
            new_name='regex_categ_priorit_864958_idx',
            old_name='regex_categ_priority_ca5335_idx',
        ),
        migrations.RenameIndex(
            model_name='regexcategorymapping',
            new_name='regex_categ_categor_eeb67a_idx',
            old_name='regex_categ_categor_8f096c_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_subtype_770fa8_idx',
            old_name='transactions_subtype_dcd943_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(default='keyword', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='accountcategorymapping',
            index=models.Index(fields=['upi_id'], name='account_cat_upi_id_8ce154_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category_source'], name='transaction_categor_4cbfc3_idx'),
        ),
    ]
