# Generated by Django 5.1.6 on 2026-04-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_parsejobstatus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParseJobStatus',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_categor_4cbfc3_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category_source',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confidence',
        ),
    ]
