# Generated by Django 5.1.6 on 2026-04-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_delete_parsejobstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(default='keyword', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category_source'], name='transaction_categor_4cbfc3_idx'),
        ),
    ]
