# Generated by Django 5.1.6 on 2026-04-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_transaction_category_source_transaction_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReparseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('failed', 'Failed'), ('done', 'Done')], default='queued', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reparse_job',
                'indexes': [models.Index(fields=['status'], name='reparse_job_status_7d1c21_idx')],
            },
        ),
    ]
