# Generated by Django 5.2.4 on 2025-07-20 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('debit', models.CharField(blank=True, max_length=50, null=True)),
                ('credit', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.CharField(blank=True, max_length=50, null=True)),
                ('source_pdf', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='smarty_raw__date_957151_idx'), models.Index(fields=['created_at'], name='smarty_raw__created_da6406_idx')],
            },
        ),
    ]
