# Generated by Django 5.2.4 on 2025-08-03 07:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarty', '0002_upi_category_mapping_dailytransactionsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raw_transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='raw_transaction',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='raw_transaction',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upi_category_mapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailytransactionsummary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='raw_transaction',
            name='date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='upi_category_mapping',
            name='upi_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='dailytransactionsummary',
            unique_together={('date', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='upi_category_mapping',
            unique_together={('upi_id', 'user')},
        ),
        migrations.AddIndex(
            model_name='raw_transaction',
            index=models.Index(fields=['upi_id'], name='smarty_raw__upi_id_6c21a8_idx'),
        ),
        migrations.AddIndex(
            model_name='raw_transaction',
            index=models.Index(fields=['category'], name='smarty_raw__categor_65ec5a_idx'),
        ),
    ]
